### ISSUE TITLE
Error in layout FloatingActionButton

### ISSUE THREAD

**Issue by giglf** [avjinder/Minimal-Todo#45]
I am trying to rewrite the program myself to learn android.
However, something go wrong when I was typing activing_main.xml.
It will get exception when android studio rendering the design.
```
java.lang.IllegalStateException: An anchor may not be changed after CoordinatorLayout measurement begins before layout is complete.
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:825)
	at android.support.design.widget.CoordinatorLayout.onLayout_Original(CoordinatorLayout.java:847)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java)
	at android.view.View.layout(View.java:17520)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17520)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17520)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at android.support.v7.widget.ActionBarOverlayLayout.onLayout_Original(ActionBarOverlayLayout.java:433)
	at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java)
	at android.view.View.layout(View.java:17520)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:17520)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:345)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:548)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:533)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:533)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$70(RenderTask.java:659)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I found the error in `FloatingActionButton`
If I modified `app:layout_anchor="@id/myCoordinatorLayout"` to `app:layout_anchor="@id/toDoRecyclerView"` .
Everything went well.
But I just finish main activity layout. I am not sure other functions will work well.
For example, function `onDependentViewChanged` in `ScrollingFABBehaviour`.

I searched in google. Somebody said it was because of _support design library_.
My setting is `compile 'com.android.support:design:24.2.1'`

**Comment by giglf** [comment]
In the previous solution will display error when there have some todoitems.
I found that I can make toDoEmptyView and RecycleView into a LinearLayout, then make app:layout_anchor={this#LinearLayout}. 
And let toolbar outside the coordinateLayout.
